data:
  vocab: ./data/tokenizers/owt-bpe
  train_set: ./data/owt_train.npy
  val_set: ./data/owt_valid.npy

experiments:
  owt_small_spec:
    vocab_size: 10000
    batch_size: 32
    context_length: 256
    num_layers: 4
    d_model: 512
    num_heads: 16
    d_ff: 1344
    theta: 10000.0

    device: cuda
    dtype: fp32
    scheduler:
      lr_max: 0.0003
      lr_min: 0.00001
      t_warmup: 1500
      t_cos: 28500
    optimizer:
      lr: 0.0003
      betas: [0.99, 0.999]
      weight_decay: 0.01
    max_grad: 1.0

    ckpt_iter: 500
    val_iter: 500
    ckpt_path: ./checkpoints
    from_ckpt: null
    max_iter: 30000
  
  owt_bf16:
    vocab_size: 10000
    batch_size: 32
    context_length: 256
    num_layers: 4
    d_model: 512
    num_heads: 16
    d_ff: 1344
    theta: 10000.0

    device: cuda
    dtype: fp32
    scheduler:
      lr_max: 0.0003
      lr_min: 0.00001
      t_warmup: 1500
      t_cos: 28500
    optimizer:
      lr: 0.0003
      betas: [0.99, 0.999]
      weight_decay: 0.01
    max_grad: 1.0

    ckpt_iter: 500
    val_iter: 500
    ckpt_path: ./checkpoints
    from_ckpt: null
    max_iter: 30000
