vocab: ./data/tokenizers/tsv2-bpe
train_set: ./data/TinyStoriesV2-GPT4-train.npy
val_set: ./data/TinyStoriesV2-GPT4-valid.npy

batch_size: 32
context_length: 512
num_layers: 2
d_model: 384
num_heads: 6
d_ff: 1536
theta: 10000.0

device: mps
dtype: fp32

lr_max: 0.0003
lr_min: 0.00001
t_warmup: 1000
t_cos: 50000

betas: [0.99, 0.999]
weight_decay: 0.01
max_grad: 1.0

ckpt_iter: 5000
val_iter: null
ckpt_path: ./checkpoints
from_ckpt: null
max_iter: null
run_id: tiny_stories_1