data:
  vocab: ./data/tokenizers/tsv2-bpe
  train_set: ./data/TinyStoriesV2-GPT4-train.npy
  val_set: ./data/TinyStoriesV2-GPT4-valid.npy

experiments:
  tiny_stories_batch_1:
    vocab_size: 10000
    batch_size: 1
    context_length: 256
    num_layers: 4
    d_model: 512
    num_heads: 16
    d_ff: 1344
    theta: 10000.0

    device: cuda
    dtype: fp32
    scheduler:
      lr_max: 0.0003
      lr_min: 0.00001
      t_warmup: 1000
      t_cos: 19000
    optimizer:
      lr: 0.0003
      betas: [0.99, 0.999]
      weight_decay: 0.01
    max_grad: 1.0

    ckpt_iter: 500
    val_iter: 500
    ckpt_path: ./checkpoints
    from_ckpt: null
    max_iter: 20000

  tiny_stories_batch_64:
    vocab_size: 10000
    batch_size: 64
    context_length: 256
    num_layers: 4
    d_model: 512
    num_heads: 16
    d_ff: 1344
    theta: 10000.0

    device: cuda
    dtype: fp32
    scheduler:
      lr_max: 0.0003
      lr_min: 0.00001
      t_warmup: 1000
      t_cos: 19000
    optimizer:
      lr: 0.0003
      betas: [0.99, 0.999]
      weight_decay: 0.01
    max_grad: 1.0

    ckpt_iter: 500
    val_iter: 500
    ckpt_path: ./checkpoints
    from_ckpt: null
    max_iter: 20000

  tiny_stories_batch_128:
    vocab_size: 10000
    batch_size: 128
    context_length: 256
    num_layers: 4
    d_model: 512
    num_heads: 16
    d_ff: 1344
    theta: 10000.0

    device: cuda
    dtype: fp32
    scheduler:
      lr_max: 0.0003
      lr_min: 0.00001
      t_warmup: 1000
      t_cos: 19000
    optimizer:
      lr: 0.0003
      betas: [0.99, 0.999]
      weight_decay: 0.01
    max_grad: 1.0

    ckpt_iter: 500
    val_iter: 500
    ckpt_path: ./checkpoints
    from_ckpt: null
    max_iter: 20000
  
  tiny_stories_batch_2048:
    vocab_size: 10000
    batch_size: 2048
    context_length: 256
    num_layers: 4
    d_model: 512
    num_heads: 16
    d_ff: 1344
    theta: 10000.0

    device: cuda
    dtype: fp32
    scheduler:
      lr_max: 0.0003
      lr_min: 0.00001
      t_warmup: 1000
      t_cos: 19000
    optimizer:
      lr: 0.0003
      betas: [0.99, 0.999]
      weight_decay: 0.01
    max_grad: 1.0

    ckpt_iter: 500
    val_iter: 500
    ckpt_path: ./checkpoints
    from_ckpt: null
    max_iter: 20000
